# configure the t8 emulator and assembler
verbose = true

[io]
[io.led] # register a memory mapped LED
addr = 0xF # allow the guest to write to 0xF
file = "led.log" # and forward all writes to led.log

[io.stdout]
addr = 0x0
file = "stdout.log"
