[package]
name = "emu"
description = "t8cpu emulator"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = {version="1.0.228", features=["derive"]}
shared = { path = "../shared" }
toml = "0.9.8"
